
name: build

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
      node-version-file:
        required: false
        type: string
        default: package.json
      pnpm-version:
        required: false
        type: string
        default: latest
      build-command:
        required: false
        type: string
        default: npm i && npm run build
      artifact-path:
        required: false
        type: string
        default: |
          build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json','**/package-lock.json') }}
          path: |
            node_modules
      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          node-version-file: ${{ inputs.node-version-file }}
      - name: setup-pnpm
        if: ${{ startsWith(inputs.build-command, 'pnpm') }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ inputs.pnpm-version }}
      - name: build
        run: ${{ inputs.build-command }}
      - id: artifact-name
        name: artifact-name
        run: |
          echo "artifact-name=${{ github.event.repository.name }}.${{ github.ref_name }}.${{ github.run_id }}" >> $GITHUB_OUTPUT
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact-name.outputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
          retention-days: 7
